sudo : required
services:
  - docker

before_install:
  - docker build -t tgavrilas/docker-react -f Dockerfile.dev .


script:
  - docker run e CI=true tgavrilas/docker-react npm run test -- --coverage
